var ConversionConstants = {
  RECEIVE_RATES_OBJECT: "RECEIVE_RATES_OBJECT",
  RECEIVE_TO_AMOUNT: "RECEIVE_TO_AMOUNT",
  RECEIVE_TO_CURRENCY: "RECEIVE_TO_CURRENCY"
};

module.exports = ConversionConstants;
