var TransfersConstants = {
	RECEIVE_TRANSFERS: "RECEIVE_TRANSFERS",
	RECEIVE_TRANSFER: "RECEIVE_TRANSFER",
	RECEIVE_HISTORICAL_RATES: "RECEIVE_HISTORICAL_RATES",
	ERROR: "ERROR"
};

module.exports = TransfersConstants;
